const types = {
  "10": { name: "fire", color: "#F08030", darkText: true },
  "12": { name: "grass", color: "#78C850", darkText: true },
  "11": { name: "water", color: "#1703ab", darkText: false },
  "1": { name: "normal", color: "#A8A888", darkText: true },
  "3": { name: "flying", color: "#A890F0", darkText: true },
  "2": { name: "fighting", color: "#991900", darkText: false },
  "18": { name: "fairy", color: "#ff6bd5", darkText: true },
  "5": { name: "ground", color: "#784411", darkText: false },
  "9": { name: "steel", color: "#ededed", darkText: true },
  "17": { name: "dark", color: "#47321c", darkText: false },
  "16": { name: "dragon", color: "#7e00a1", darkText: false },
  "13": { name: "electric", color: "#fffb00", darkText: true },
  "8": { name: "ghost", color: "#6200b8", darkText: false },
  "7": { name: "bug", color: "#b8de40", darkText: true },
  "14": { name: "psychic", color: "#e300aa", darkText: true },
  "6": { name: "rock", color: "#B8A038", darkText: true },
  "15": { name: "ice", color: "#4de7ff", darkText: true },
  "4": { name: "poison", color: "#9c0091", darkText: false },
};
export default types;
