const types = {
  fire: { color: "#F08030", darkText: true },
  grass: { color: "#78C850", darkText: true },
  water: { color: "#1703ab", darkText: false },
  normal: { color: "#A8A878", darkText: true },
  flying: { color: "#A890F0", darkText: true },
  fighting: { color: "#991900", darkText: false },
  fairy: { color: "#ff6bd5", darkText: true },
  ground: { color: "#784411", darkText: false },
  steel: { color: "#adadad", darkText: true },
  dark: { color: "#47321c", darkText: false },
  dragon: { color: "#7e00a1", darkText: false },
  electric: { color: "#fffb00", darkText: true },
  ghost: { color: "#6200b8", darkText: false },
  bug: { color: "#68de40", darkText: true },
  psychic: { color: "#e300aa", darkText: true },
  rock: { color: "#B8A038", darkText: true },
  ice: { color: "#4de7ff", darkText: true },
  poison: { color: "#9c0091", darkText: false },
};
export default types;
